-- Knowledge Hub resources.
-- Run once in Supabase SQL Editor, then rerun safely when seed resources change.

create table if not exists public.knowledge_resources (
  id            text primary key,
  title         text not null,
  description   text not null,
  category      text not null,
  source_name   text not null,
  source_url    text not null,
  resource_type text not null default 'Guide',
  read_time     text not null default 'Read',
  image_url     text,
  is_featured   boolean not null default false,
  is_trending   boolean not null default false,
  is_active     boolean not null default true,
  sort_order    integer not null default 0,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

alter table public.knowledge_resources enable row level security;

drop policy if exists "knowledge_resources_read" on public.knowledge_resources;

create policy "knowledge_resources_read"
  on public.knowledge_resources for select
  using (is_active = true);

insert into public.knowledge_resources (
  id, title, description, category, source_name, source_url, resource_type,
  read_time, image_url, is_featured, is_trending, sort_order
) values
  (
    'acog-postpartum-care',
    'Postpartum care and the weeks after birth',
    'ACOG guidance on postpartum visits, recovery questions, emotions, breastfeeding, contraception, and future health.',
    'Postpartum',
    'ACOG',
    'https://www.acog.org/womens-health/faqs/having-a-baby',
    'FAQ',
    '8 min read',
    'https://images.unsplash.com/photo-1544126592-807ade215a0b?w=600',
    true,
    true,
    1
  ),
  (
    'acog-exercise-after-pregnancy',
    'Exercise after pregnancy',
    'When movement can resume after birth, how to restart safely, and why postpartum activity supports recovery.',
    'Postpartum',
    'ACOG',
    'https://www.acog.org/womens-health/faqs/exercise-after-pregnancy',
    'FAQ',
    '7 min read',
    'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600',
    true,
    false,
    2
  ),
  (
    'acog-postpartum-depression',
    'Postpartum depression: signs and support',
    'ACOG guidance on baby blues, postpartum depression, when to call your ob-gyn, and treatment options.',
    'Postpartum',
    'ACOG',
    'https://www.acog.org/womens-health/faqs/postpartum-depression',
    'FAQ',
    '8 min read',
    'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600',
    false,
    true,
    3
  ),
  (
    'acog-postpartum-birth-control',
    'Postpartum birth control options',
    'A practical guide to choosing contraception after birth, including timing and breastfeeding considerations.',
    'Postpartum',
    'ACOG',
    'https://www.acog.org/womens-health/faqs/postpartum-birth-control',
    'FAQ',
    '9 min read',
    'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600',
    false,
    false,
    4
  ),
  (
    'cdc-pregnancy-vaccines',
    'Vaccine recommendations during pregnancy',
    'CDC recommendations for vaccines before, during, and after pregnancy to help protect mother and baby.',
    'Pregnancy',
    'CDC',
    'https://www.cdc.gov/vaccines-pregnancy/recommended-vaccines/index.html',
    'Guide',
    '6 min read',
    'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600',
    true,
    false,
    5
  ),
  (
    'aap-umbilical-cord-care',
    'Umbilical cord care in newborns',
    'AAP guidance on keeping the cord stump clean and dry, warning signs, and when to call the pediatrician.',
    'Newborn Care',
    'HealthyChildren.org / AAP',
    'https://www.healthychildren.org/English/ages-stages/baby/bathing-skin-care/pages/Umbilical-Cord-Care.aspx',
    'Guide',
    '5 min read',
    'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600',
    true,
    false,
    6
  ),
  (
    'cdc-breastfeeding-guidance',
    'Breastfeeding recommendations and guidance',
    'CDC guidance on breastfeeding duration, expressed milk, cleaning feeding items, and support systems.',
    'Feeding & Nutrition',
    'CDC',
    'https://www.cdc.gov/breastfeeding/php/guidelines-recommendations/index.html',
    'Guide',
    '6 min read',
    'https://images.unsplash.com/photo-1590641935647-1c8f2d4f1f59?w=600',
    false,
    true,
    7
  ),
  (
    'cdc-vitamin-d-breastfeeding',
    'Vitamin D and breastfeeding',
    'CDC information on vitamin D needs for breastfed and partially breastfed infants.',
    'Feeding & Nutrition',
    'CDC',
    'https://www.cdc.gov/breastfeeding-special-circumstances/hcp/diet-micronutrients/vitamin-d.html',
    'Clinical note',
    '4 min read',
    'https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?w=600',
    false,
    false,
    8
  ),
  (
    'cdc-safe-sleep',
    'Helping babies sleep safely',
    'CDC safe sleep steps based on AAP recommendations to reduce sleep-related infant death risk.',
    'Sleep & Safety',
    'CDC',
    'https://www.cdc.gov/sudden-infant-death/sleep-safely/index.html',
    'Safety guide',
    '7 min read',
    'https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=600',
    true,
    true,
    10
  ),
  (
    'aap-safe-sleep',
    'AAP policy explained: safe sleep',
    'AAP safe sleep recommendations explained for families, including back sleeping and a firm, flat surface.',
    'Sleep & Safety',
    'HealthyChildren.org / AAP',
    'https://www.healthychildren.org/English/ages-stages/baby/sleep/Pages/A-Parents-Guide-to-Safe-Sleep.aspx',
    'Policy explainer',
    '10 min read',
    'https://images.unsplash.com/photo-1546015720-b8b30df5aa27?w=600',
    false,
    false,
    9
  ),
  (
    'cdc-developmental-milestones',
    'CDC developmental milestones',
    'Milestone checklists and guidance for tracking how children play, learn, speak, act, and move.',
    'Child Development',
    'CDC',
    'https://www.cdc.gov/milestones',
    'Checklist hub',
    '6 min read',
    'https://images.unsplash.com/photo-1566004100631-35d015d6a491?w=600',
    true,
    true,
    11
  ),
  (
    'cdc-positive-parenting-infants',
    'Positive parenting tips for infants',
    'CDC tips for nurturing, protecting, and supporting development during the first year.',
    'Child Development',
    'CDC',
    'https://www.cdc.gov/child-development/positive-parenting-tips/infants.html',
    'Guide',
    '6 min read',
    'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=600',
    false,
    false,
    12
  ),
  (
    'acog-postpartum-recovery-video',
    'Postpartum recovery after birth',
    'ACOG video resource on physical and emotional recovery after having a baby.',
    'Postpartum',
    'ACOG',
    'https://www.acog.org/womens-health/videos/postpartum-recovery',
    'Video',
    'Watch',
    'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600',
    true,
    false,
    13
  ),
  (
    'cdc-hear-her-stories-video',
    'Hear Her: pregnancy and postpartum warning signs',
    'CDC campaign videos and stories that help families recognize urgent maternal warning signs.',
    'Postpartum',
    'CDC',
    'https://www.cdc.gov/hearher/personal-stories/index.html',
    'Video',
    'Watch',
    'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600',
    false,
    true,
    14
  ),
  (
    'nichd-safe-to-sleep-videos',
    'Safe to Sleep videos',
    'NICHD videos for families on creating a safe sleep environment for babies.',
    'Sleep & Safety',
    'NICHD',
    'https://safetosleep.nichd.nih.gov/resources/social-digital/videos',
    'Video',
    'Watch',
    'https://images.unsplash.com/photo-1546015720-b8b30df5aa27?w=600',
    false,
    false,
    15
  ),
  (
    'cdc-milestones-videos',
    'Milestones in action videos',
    'CDC video examples of developmental milestones by age to help parents know what to look for.',
    'Child Development',
    'CDC',
    'https://www.cdc.gov/ncbddd/actearly/milestones/milestones-in-action.html',
    'Video',
    'Watch',
    'https://images.unsplash.com/photo-1566004100631-35d015d6a491?w=600',
    false,
    false,
    16
  ),
  (
    'acog-postpartum-depression-audio',
    'Postpartum depression podcast',
    'ACOG audio conversation about postpartum depression, symptoms, and getting help.',
    'Postpartum',
    'ACOG',
    'https://www.acog.org/womens-health/experts-and-stories/the-latest/postpartum-depression',
    'Audio',
    'Listen',
    'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=600',
    false,
    true,
    17
  ),
  (
    'nih-safe-to-sleep-audio',
    'Safe infant sleep audio resources',
    'NICHD Safe to Sleep audio and media resources for family education.',
    'Sleep & Safety',
    'NICHD',
    'https://safetosleep.nichd.nih.gov/resources/social-digital/audio',
    'Audio',
    'Listen',
    'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=600',
    false,
    false,
    18
  )
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  source_name = excluded.source_name,
  source_url = excluded.source_url,
  resource_type = excluded.resource_type,
  read_time = excluded.read_time,
  image_url = excluded.image_url,
  is_featured = excluded.is_featured,
  is_trending = excluded.is_trending,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order,
  updated_at = now();
