-- Pregnancy guidance: Weeks 11–20
-- Paste into Supabase SQL Editor and run.

insert into public.pregnancy_guidance (
  week, baby_this_week, your_body, symptoms, important_nutrients,
  helpful_foods, things_to_limit, helpful_practices, good_habits,
  emotional_wellness, whats_normal, checklist, contact_doctor,
  partner_support, encouragement, baby_size_emoji, baby_size_object, baby_length_cm
) values

(11,
 'Your baby is growing rapidly and looking more like a tiny human every day. Your baby is now about the size of a fig. Important development continues, including rapid brain development, facial features becoming clearer, fingers and toes fully formed, tiny fingernails beginning to grow, and bones starting to harden. Your baby may already be stretching, kicking, swallowing fluid, and making tiny movements, although you still cannot feel movement yet. Major organs continue maturing and beginning to function together.',
 'Your body continues adjusting to pregnancy hormones and your growing baby. During Week 11, blood volume continues increasing, the uterus continues growing, metabolism works harder, and hormone levels remain high. Some women may begin noticing slight belly fullness, tighter clothes, more visible veins, and changes in skin or hair. Fatigue and nausea may still continue, although some women slowly begin noticing symptom improvement.',
 '["Nausea or morning sickness","Fatigue","Bloating","Breast tenderness","Constipation","Headaches","Food cravings or aversions","Emotional sensitivity","Increased urination"]',
 '["Folic acid","Protein","Iron","Calcium","Omega-3 fats","Fiber","Hydration"]',
 '["Fruits","Vegetables","Whole grains","Lentils and beans","Yogurt and dairy","Eggs","Nuts and seeds"]',
 '["Alcohol","Smoking","Excess caffeine","Raw or undercooked foods"]',
 '["Prioritize rest","Gentle walking","Light stretching","Stay hydrated","Take breaks when tired"]',
 '["Continue prenatal vitamins","Listen to your body","Avoid overexertion","Sleep whenever needed"]',
 'Week 11 can bring a mix of emotions. You may feel excited, emotional, anxious, relieved, overwhelmed, or impatient. Some women may begin feeling more connected to pregnancy after scans or symptoms become more noticeable. Others may still feel uncertain or anxious. Both experiences are completely valid.',
 '["Nausea","Fatigue","Bloating","Emotional ups and downs","Constipation","Food aversions","Headaches","Little or no symptoms"]',
 '["Continue prenatal vitamins","Stay hydrated","Eat small balanced meals","Prioritize rest and sleep","Avoid smoking and alcohol","Reduce excess caffeine","Attend prenatal appointments if scheduled","Prepare questions for upcoming scans and checkups"]',
 '["Heavy bleeding","Severe abdominal pain","Fever","Fainting","Severe dizziness","Severe one-sided pelvic pain","Persistent vomiting causing dehydration"]',
 '["Help with meals and snacks","Support extra rest","Reduce stress","Offer reassurance","Attend appointments together"]',
 'Your baby is growing and developing in amazing ways every single day. Even if pregnancy feels tiring or emotional right now, your body is doing extraordinary work behind the scenes. You do not need to do everything perfectly. Rest, nourishment, hydration, and kindness toward yourself are already beautiful ways to support both you and your growing baby.',
 '🍋', 'Fig', 4.1),

(12,
 'Your baby is growing rapidly and entering an exciting stage of development. Your baby is now about the size of a lime. Important development continues, including facial features becoming more defined, fingers and toes fully formed, tiny fingernails developing, digestive system beginning to function, and muscles and reflexes becoming stronger. Your baby may already be stretching, kicking, swallowing, and opening and closing tiny hands, although you still likely cannot feel movement yet. Most major organs are now formed and will continue growing and maturing throughout pregnancy.',
 'Your body continues adapting to your growing pregnancy. During Week 12, the uterus continues expanding, blood volume increases, hormone levels remain elevated, and the placenta takes over more hormone production. For some women, first-trimester symptoms may slowly begin easing around this stage. Others may still experience nausea and fatigue strongly. Both experiences can be completely normal.',
 '["Nausea or morning sickness","Fatigue","Bloating","Breast tenderness","Constipation","Headaches","Food cravings or aversions","Emotional sensitivity","Increased urination"]',
 '["Folic acid","Protein","Iron","Calcium","Omega-3 fats","Fiber","Hydration"]',
 '["Fruits","Vegetables","Whole grains","Lentils and beans","Eggs","Yogurt and dairy","Nuts and seeds"]',
 '["Alcohol","Smoking","Excess caffeine","Raw or undercooked foods"]',
 '["Prioritize sleep and rest","Gentle walking","Prenatal stretching if comfortable","Stay hydrated","Take breaks often"]',
 '["Continue prenatal vitamins","Listen to your body","Avoid overexertion","Wear comfortable clothing","Rest whenever needed"]',
 'Week 12 can feel emotional and exciting for many women. You may feel relieved, hopeful, emotional, anxious, excited, or overwhelmed. For many families, reaching Week 12 can feel like an important milestone. Some women may still feel worried about scans, miscarriage, symptoms, or whether baby is developing normally. Gentle reminder: Pregnancy emotions are valid and normal.',
 '["Nausea","Fatigue","Bloating","Emotional ups and downs","Constipation","Headaches","Breast tenderness","Little or no symptoms"]',
 '["Continue prenatal vitamins","Stay hydrated","Eat balanced meals","Prioritize sleep and rest","Avoid smoking and alcohol","Reduce excess caffeine","Attend prenatal appointments and scans","Prepare questions for upcoming checkups"]',
 '["Heavy bleeding","Severe abdominal pain","Fever","Fainting","Severe dizziness","Severe one-sided pelvic pain","Persistent vomiting causing dehydration"]',
 '["Offer emotional reassurance","Support healthy routines","Help with meals and snacks","Reduce stress","Attend appointments together"]',
 'You have already come through so many important early changes and milestones. Your body is doing extraordinary work every single day — even on the hard and exhausting days. You do not need to handle pregnancy perfectly. Rest, nourishment, hydration, emotional support, and kindness toward yourself are already beautiful ways to care for both you and your growing baby.',
 '🍋', 'Lime', 5.4),

(13,
 'Welcome to the beginning of the second trimester. Your baby is now about the size of a lemon. Important development continues, including bones becoming stronger, facial features becoming more defined, fingerprints beginning to form, vocal cords developing, and digestive system continuing to mature. Your baby may already be moving arms and legs, stretching, swallowing amniotic fluid, and practising tiny reflexes. Although movement is happening, most women still cannot feel it yet. Your baby''s body is growing quickly while major organs continue maturing.',
 'Your body is continuing to adapt to your growing pregnancy. During Week 13, the uterus continues expanding, blood volume increases further, hormone levels begin stabilizing slightly, and the placenta takes over more pregnancy support. Some women begin feeling slightly more energetic, less nauseous, and emotionally lighter. Others may still experience strong first-trimester symptoms. Both experiences can be completely normal.',
 '["Fatigue","Bloating","Breast tenderness","Mild headaches","Constipation","Increased appetite","Emotional changes","Increased discharge"]',
 '["Protein","Iron","Calcium","Folic acid","Omega-3 fats","Fiber","Hydration"]',
 '["Fruits","Vegetables","Whole grains","Lentils and beans","Eggs","Dairy products","Nuts and seeds"]',
 '["Alcohol","Smoking","Excess caffeine","Raw or undercooked foods"]',
 '["Gentle walking","Prenatal stretching or yoga if comfortable","Prioritize sleep and rest","Stay hydrated","Take breaks when needed"]',
 '["Continue prenatal vitamins","Wear comfortable clothing","Listen to your body","Avoid overexertion"]',
 'Week 13 can bring many emotions. You may feel relieved, hopeful, excited, emotional, anxious, or more connected to pregnancy. For many families, entering the second trimester feels like an important emotional milestone. Some women may still worry about scans, symptom changes, baby''s development, or upcoming months. Gentle reminder: Pregnancy emotions naturally rise and fall.',
 '["Fatigue","Bloating","Constipation","Emotional ups and downs","Breast tenderness","Mild cramping or stretching sensations","Increased appetite","Little or no symptoms"]',
 '["Continue prenatal vitamins","Stay hydrated","Eat balanced meals","Prioritize sleep and rest","Gentle physical activity if comfortable","Attend prenatal appointments if scheduled","Wear comfortable supportive clothing","Continue avoiding smoking and alcohol"]',
 '["Heavy bleeding","Severe abdominal pain","Fever","Severe dizziness","Fainting","Severe vomiting causing dehydration","Severe one-sided pelvic pain"]',
 '["Encourage healthy habits","Help with meals and snacks","Support rest and relaxation","Attend appointments together","Offer emotional reassurance"]',
 'You are entering a brand new phase of pregnancy. Your body has already done incredible work to support your growing baby through the first trimester. Even on difficult days, you are doing enough. Rest, nourishment, emotional support, hydration, and kindness toward yourself continue to be beautiful ways to care for both you and your baby.',
 '🍑', 'Lemon', 7.4),

(14,
 'Your baby is growing quickly and becoming more active during Week 14. Your baby is now about the size of a peach. Important development continues, including facial expressions beginning, neck becoming stronger, body becoming more proportionate, tiny hair beginning to form, and muscles and movements improving. Your baby may already be stretching, kicking, swallowing, and moving facial muscles. Although movement is happening, many women still cannot feel it yet — especially during a first pregnancy. Your baby''s organs continue maturing and growing stronger every day.',
 'Many women officially begin feeling more pregnant during Week 14. During this stage, the uterus continues expanding upward, blood volume increases further, energy levels may slowly improve, and nausea may begin easing for some women. Some women notice a small baby bump, increased appetite, and less exhaustion compared to the first trimester. Others may still experience fatigue and nausea. Both experiences can be completely normal.',
 '["Bloating","Fatigue","Breast tenderness","Increased appetite","Constipation","Mild headaches","Emotional changes","Increased discharge"]',
 '["Protein","Iron","Calcium","Folic acid","Omega-3 fats","Fiber","Hydration"]',
 '["Fruits","Vegetables","Whole grains","Lentils and beans","Eggs","Dairy products","Nuts and seeds"]',
 '["Alcohol","Smoking","Excess caffeine","Raw or undercooked foods"]',
 '["Gentle walking","Prenatal yoga or stretching if comfortable","Prioritize sleep and rest","Stay hydrated","Wear comfortable supportive clothing"]',
 '["Continue prenatal vitamins","Avoid overexertion","Listen to your body","Take breaks when needed"]',
 'Week 14 can feel exciting and emotionally reassuring for many women. You may feel hopeful, excited, emotional, more connected to pregnancy, occasionally anxious, or relieved to enter the second trimester. Some women may still worry about scans, baby''s health, body changes, future delivery, and parenting. Gentle reminder: Pregnancy emotions naturally rise and fall.',
 '["Bloating","Mild cramping or stretching sensations","Constipation","Emotional ups and downs","Breast tenderness","Increased appetite","Little or no symptoms"]',
 '["Continue prenatal vitamins","Stay hydrated","Eat balanced meals","Gentle physical activity if comfortable","Prioritize sleep and rest","Attend prenatal appointments if scheduled","Wear comfortable supportive clothing","Continue avoiding smoking and alcohol"]',
 '["Heavy bleeding","Severe abdominal pain","Fever","Severe dizziness","Fainting","Severe vomiting causing dehydration","Severe one-sided pelvic pain"]',
 '["Support healthy habits","Help with meals and snacks","Encourage rest and relaxation","Attend appointments together","Offer emotional reassurance"]',
 'You have already come through so many important early changes and milestones. Your body is growing, adapting, and supporting your baby in extraordinary ways every single day. Even on tiring or emotional days, you are already doing something incredible. Rest, nourishment, hydration, emotional support, and kindness toward yourself continue to be beautiful ways to care for both you and your growing baby.',
 '🍋', 'Peach', 8.7),

(15,
 'Your baby is growing rapidly and becoming more active during Week 15. Your baby is now about the size of an apple. Important development continues, including bones becoming stronger, muscles growing stronger, ears moving into position, tiny facial expressions developing, and body movements becoming more coordinated. Your baby may already be stretching, kicking, swallowing amniotic fluid, and moving arms and legs actively. Although many first-time moms may not feel movement yet, some women may begin noticing tiny flutter-like sensations soon. Your baby''s skin is still very thin and delicate at this stage.',
 'Your body continues adapting to your growing pregnancy. During Week 15, the uterus continues expanding upward, blood volume keeps increasing, energy levels may improve, and appetite often increases. Many women begin feeling physically more comfortable, emotionally lighter than the first trimester, and more aware of body changes. Some women may still experience fatigue, nausea, and headaches. Both experiences can be completely normal.',
 '["Growing belly","Bloating","Increased appetite","Constipation","Mild headaches","Breast changes","Emotional sensitivity","Increased discharge"]',
 '["Protein","Iron","Calcium","Folic acid","Omega-3 fats","Fiber","Hydration"]',
 '["Fruits","Vegetables","Whole grains","Lentils and beans","Eggs","Yogurt and dairy","Nuts and seeds"]',
 '["Alcohol","Smoking","Excess caffeine","Raw or undercooked foods"]',
 '["Gentle walking","Prenatal yoga or stretching if comfortable","Prioritize rest and sleep","Stay hydrated","Wear supportive comfortable clothing"]',
 '["Continue prenatal vitamins","Avoid overexertion","Change positions slowly if dizzy","Take breaks when needed"]',
 'Week 15 can feel exciting and emotional. You may feel hopeful, more connected to pregnancy, emotional, excited, occasionally anxious, or more confident. Some women may still worry about baby''s health, scans and appointments, body changes, and future labor and parenting. Gentle reminder: Pregnancy emotions naturally change from week to week.',
 '["Bloating","Mild cramping or stretching sensations","Constipation","Emotional ups and downs","Increased appetite","Mild fatigue","Little or no symptoms"]',
 '["Continue prenatal vitamins","Stay hydrated","Eat balanced nutritious meals","Gentle physical activity if comfortable","Prioritize sleep and rest","Attend prenatal appointments if scheduled","Wear comfortable supportive clothing","Continue avoiding smoking and alcohol"]',
 '["Heavy bleeding","Severe abdominal pain","Fever","Severe dizziness","Fainting","Severe headaches with vision changes","Severe vomiting or dehydration"]',
 '["Encourage healthy habits","Help with meals and snacks","Support rest and relaxation","Attend appointments together","Offer reassurance and emotional support"]',
 'Your baby is growing stronger and more active every single day. Your body is doing extraordinary work quietly behind the scenes — even on days when you feel tired, emotional, or uncomfortable. You do not need to handle pregnancy perfectly. Rest, nourishment, hydration, movement, emotional support, and kindness toward yourself continue to be beautiful ways to care for both you and your growing baby.',
 '🍎', 'Apple', 10.1),

(16,
 'Your baby is growing quickly and becoming much more active during Week 16. Your baby is now about the size of an avocado. Important development continues, including stronger muscles and movements, facial muscles becoming more expressive, ears moving closer to final position, bones continuing to harden, and nervous system developing rapidly. Your baby may already be stretching, kicking, sucking tiny thumbs, swallowing amniotic fluid, and making facial expressions. Some women — especially in second pregnancies — may begin noticing tiny fluttering movements called quickening around this stage.',
 'Your body continues adapting beautifully to your growing pregnancy. During Week 16, the uterus continues expanding upward, blood volume increases further, energy levels may improve, and the baby bump may become more noticeable. Many women begin feeling physically more comfortable, more energetic, and emotionally more connected to pregnancy. Some women may still experience fatigue, headaches, and mild nausea. Both experiences can still be completely normal.',
 '["Growing belly","Bloating","Increased appetite","Constipation","Mild back discomfort","Breast changes","Emotional sensitivity","Increased discharge"]',
 '["Protein","Iron","Calcium","Folic acid","Omega-3 fats","Fiber","Hydration"]',
 '["Fruits","Vegetables","Whole grains","Lentils and beans","Eggs","Dairy products","Nuts and seeds"]',
 '["Alcohol","Smoking","Excess caffeine","Raw or undercooked foods"]',
 '["Gentle walking","Prenatal yoga or stretching if comfortable","Prioritize rest and sleep","Stay hydrated","Wear comfortable supportive clothing"]',
 '["Continue prenatal vitamins","Avoid standing too long","Change positions slowly if dizzy","Rest when needed"]',
 'Week 16 can feel exciting and reassuring for many women. You may feel hopeful, more connected to baby, emotional, excited, occasionally anxious, or more confident. Some women may still worry about baby''s health, upcoming anatomy scans, body changes, and labor and parenting. Gentle reminder: Pregnancy emotions naturally rise and fall throughout the journey.',
 '["Bloating","Mild stretching or cramping sensations","Constipation","Emotional ups and downs","Increased appetite","Mild fatigue","Occasional dizziness","Little or no symptoms"]',
 '["Continue prenatal vitamins","Stay hydrated","Eat balanced nutritious meals","Gentle physical activity if comfortable","Prioritize sleep and rest","Attend prenatal appointments if scheduled","Wear comfortable supportive clothing","Continue avoiding smoking and alcohol"]',
 '["Heavy bleeding","Severe abdominal pain","Fever","Severe dizziness or fainting","Severe headaches with vision changes","Painful urination","Severe swelling or dehydration"]',
 '["Support healthy habits","Help with meals and snacks","Encourage rest and relaxation","Attend appointments together","Offer emotional reassurance"]',
 'Your baby is growing stronger, more active, and more developed every single day. Your body is doing extraordinary work — even when you feel tired, emotional, or uncomfortable. You are already doing enough. Rest, nourishment, movement, hydration, emotional support, and kindness toward yourself continue to be beautiful ways to care for both you and your growing baby.',
 '🥑', 'Avocado', 11.6),

(17,
 'Your baby is growing rapidly and becoming even more active during Week 17. Your baby is now about the size of a pear. Important development continues, including stronger muscles and movements, fat beginning to develop under the skin, skeleton continuing to harden, hearing becoming more developed, and fingerprints forming. Your baby may already be stretching, rolling, kicking, swallowing amniotic fluid, and practising sucking movements. Many babies are becoming very active inside the womb now, although some moms may still not feel movement yet.',
 'Your body continues adjusting beautifully to support your growing baby. During Week 17, the uterus continues expanding upward, blood volume increases significantly, posture and balance begin changing, and the baby bump may become more noticeable. Many women begin feeling increased appetite, more energy compared to the first trimester, and occasional body aches or stretching sensations. Some women may also begin feeling early baby flutters around this stage.',
 '["Growing belly","Increased appetite","Mild back discomfort","Bloating","Constipation","Breast changes","Emotional sensitivity","Increased discharge"]',
 '["Protein","Iron","Calcium","Folic acid","Omega-3 fats","Fiber","Hydration"]',
 '["Fruits","Vegetables","Whole grains","Lentils and beans","Eggs","Dairy products","Nuts and seeds"]',
 '["Alcohol","Smoking","Excess caffeine","Raw or undercooked foods"]',
 '["Gentle walking","Prenatal yoga or stretching if comfortable","Prioritize rest and sleep","Stay hydrated","Use supportive pillows while sleeping"]',
 '["Continue prenatal vitamins","Avoid standing too long","Change positions slowly","Rest when your body asks for it"]',
 'Week 17 can feel exciting and emotional. You may feel more connected to baby, excited, hopeful, emotional, occasionally anxious, or curious about upcoming scans. Some women may still worry about baby''s development, movement patterns, body changes, and labor and parenting. Gentle reminder: Pregnancy emotions naturally change throughout the journey.',
 '["Mild stretching or cramping sensations","Bloating","Constipation","Increased appetite","Emotional ups and downs","Mild back discomfort","Occasional dizziness","Little or no symptoms"]',
 '["Continue prenatal vitamins","Stay hydrated","Eat balanced nutritious meals","Gentle physical activity if comfortable","Prioritize sleep and rest","Attend prenatal appointments if scheduled","Wear supportive comfortable clothing","Continue avoiding smoking and alcohol"]',
 '["Heavy bleeding","Severe abdominal pain","Fever","Severe dizziness or fainting","Severe headaches with vision changes","Painful urination","Severe swelling or dehydration"]',
 '["Support healthy habits","Help with meals and snacks","Encourage rest and relaxation","Attend appointments together","Offer emotional reassurance"]',
 'Your baby is growing stronger, more active, and more developed every single day. Even on difficult or emotional days, your body is doing incredible work quietly behind the scenes. You do not need to do everything perfectly. Rest, nourishment, hydration, movement, emotional support, and kindness toward yourself continue to be beautiful ways to care for both you and your growing baby.',
 '🍐', 'Pear', 13.0),

(18,
 'Your baby is growing quickly and becoming much more active during Week 18. Your baby is now about the size of a sweet potato. Important development continues, including stronger muscles and movements, ears becoming more developed for hearing, nervous system growing rapidly, fat beginning to form under the skin, and fingerprints becoming more detailed. Your baby may already be rolling, stretching, kicking, hiccuping, and swallowing amniotic fluid. Many women begin feeling more noticeable baby movements around this stage, especially fluttering or tiny kicks.',
 'Your body continues adapting beautifully to your growing baby. During Week 18, the uterus expands further upward, posture and balance continue changing, blood volume increases significantly, and the baby bump becomes more noticeable. Many women begin noticing more frequent baby movement, increased appetite, mild back discomfort, and stretching sensations around the belly. Your center of gravity may slowly shift as your belly grows.',
 '["Growing belly","Baby flutters or kicks","Mild back pain","Bloating","Constipation","Increased appetite","Emotional sensitivity","Breast changes"]',
 '["Protein","Iron","Calcium","Folic acid","Omega-3 fats","Fiber","Hydration"]',
 '["Fruits","Vegetables","Whole grains","Lentils and beans","Eggs","Dairy products","Nuts and seeds"]',
 '["Alcohol","Smoking","Excess caffeine","Raw or undercooked foods"]',
 '["Gentle walking","Prenatal yoga or stretching if comfortable","Prioritize sleep and rest","Use supportive pillows while sleeping","Stay hydrated"]',
 '["Continue prenatal vitamins","Avoid standing too long","Change positions slowly","Rest when needed"]',
 'Week 18 can feel exciting and emotional. You may feel more connected to baby, excited about movement, emotional, hopeful, occasionally anxious, or curious about anatomy scans. Feeling baby movement for the first time can feel emotional and reassuring for many women. Some women may still worry about baby''s development, movement patterns, scans and appointments, and body changes. Gentle reminder: Every pregnancy journey looks different.',
 '["Mild stretching or cramping sensations","Bloating","Constipation","Increased appetite","Mild back discomfort","Emotional ups and downs","Occasional dizziness","Baby flutters or kicks"]',
 '["Continue prenatal vitamins","Stay hydrated","Eat balanced nutritious meals","Gentle physical activity if comfortable","Prioritize sleep and rest","Attend prenatal appointments if scheduled","Wear supportive comfortable clothing","Continue avoiding smoking and alcohol"]',
 '["Heavy bleeding","Severe abdominal pain","Fever","Severe dizziness or fainting","Severe headaches with vision changes","Painful urination","Severe swelling or dehydration"]',
 '["Support healthy habits","Help with meals and snacks","Encourage rest and relaxation","Attend appointments together","Share excitement about baby movement"]',
 'Your baby is growing stronger, more active, and more responsive every single day. Even when pregnancy feels physically uncomfortable or emotionally overwhelming, your body is doing incredible work quietly behind the scenes. You are already doing enough. Rest, nourishment, movement, hydration, emotional support, and kindness toward yourself continue to be beautiful ways to care for both you and your growing baby.',
 '🫑', 'Sweet potato', 14.2),

(19,
 'Your baby is growing rapidly and becoming more active and responsive during Week 19. Your baby is now about the size of a mango. Important development continues, including brain and nervous system growth, stronger muscles and movements, development of senses like hearing, protective coating called vernix forming on the skin, and arms and legs becoming more proportionate. Your baby may already be kicking, rolling, stretching, swallowing amniotic fluid, and reacting to sounds and movement. Many women begin feeling more regular baby movements around this stage.',
 'Your body continues adjusting beautifully to support your growing baby. During Week 19, the uterus expands further upward, your belly becomes more noticeable, posture and balance continue changing, and blood circulation increases significantly. Many women notice stronger baby flutters or kicks, stretching sensations, increased appetite, and changes in sleep comfort. Your center of gravity may continue shifting as your bump grows.',
 '["Baby kicks or fluttering movements","Growing belly","Mild back discomfort","Bloating","Constipation","Increased appetite","Emotional sensitivity","Breast changes"]',
 '["Protein","Iron","Calcium","Folic acid","Omega-3 fats","Fiber","Hydration"]',
 '["Fruits","Vegetables","Whole grains","Lentils and beans","Eggs","Dairy products","Nuts and seeds"]',
 '["Alcohol","Smoking","Excess caffeine","Raw or undercooked foods"]',
 '["Gentle walking","Prenatal yoga or stretching if comfortable","Use supportive pillows while sleeping","Prioritize rest and sleep","Stay hydrated"]',
 '["Continue prenatal vitamins","Avoid standing too long","Change positions slowly","Rest whenever needed"]',
 'Week 19 can feel exciting, emotional, and reassuring. You may feel more connected to baby, excited about movements, emotional, hopeful, occasionally anxious, or curious about upcoming scans. Feeling movement more regularly can help pregnancy feel more real emotionally for many women. Some women may still worry about baby''s health, anatomy scans, body changes, and labor and parenting. Gentle reminder: Every pregnancy journey is unique.',
 '["Baby movements or flutters","Bloating","Constipation","Mild stretching or cramping sensations","Emotional ups and downs","Increased appetite","Mild back discomfort","Occasional dizziness"]',
 '["Continue prenatal vitamins","Stay hydrated","Eat balanced nutritious meals","Gentle physical activity if comfortable","Prioritize sleep and rest","Attend prenatal appointments and scans if scheduled","Wear supportive comfortable clothing","Continue avoiding smoking and alcohol"]',
 '["Heavy bleeding","Severe abdominal pain","Fever","Severe dizziness or fainting","Severe headaches with vision changes","Painful urination","Severe swelling or dehydration"]',
 '["Support healthy habits","Help with meals and snacks","Encourage rest and relaxation","Attend appointments together","Share excitement about baby movement"]',
 'Your baby is growing stronger, more active, and more responsive every single day. Even on tiring or emotional days, your body is doing incredible work quietly behind the scenes. You are already doing enough. Rest, nourishment, hydration, movement, emotional support, and kindness toward yourself continue to be beautiful ways to care for both you and your growing baby.',
 '🥭', 'Mango', 15.3),

(20,
 'You are halfway through pregnancy — a beautiful milestone. Your baby is now about the size of a banana. Important development continues, including stronger muscles and movements, hearing becoming more developed, sleep and wake cycles beginning, eyebrows and tiny hair forming, and protective vernix coating increasing on the skin. Your baby may already be kicking strongly, stretching, rolling, swallowing amniotic fluid, and reacting to sounds and touch. Many women begin feeling more regular and noticeable baby movements around this stage.',
 'Your body continues adapting beautifully to support your growing baby. During Week 20, the uterus reaches around belly button level, posture and balance continue shifting, blood volume increases significantly, and the baby bump becomes much more noticeable. Many women notice stronger baby kicks, increased appetite, stretching sensations, mild body aches, and changing sleep comfort. Some women may also begin experiencing more pressure in the lower belly as the uterus grows.',
 '["Regular baby movements","Growing belly","Mild back discomfort","Bloating","Constipation","Increased appetite","Emotional sensitivity","Breast changes"]',
 '["Protein","Iron","Calcium","Folic acid","Omega-3 fats","Fiber","Hydration"]',
 '["Fruits","Vegetables","Whole grains","Lentils and beans","Eggs","Dairy products","Nuts and seeds"]',
 '["Alcohol","Smoking","Excess caffeine","Raw or undercooked foods"]',
 '["Gentle walking","Prenatal yoga or stretching if comfortable","Use supportive pillows while sleeping","Prioritize rest and sleep","Stay hydrated"]',
 '["Continue prenatal vitamins","Avoid standing too long","Change positions slowly","Rest when your body asks for it"]',
 'Week 20 can feel exciting and emotional. You may feel more connected to baby, excited about movements, emotional, hopeful, occasionally anxious, or more aware that pregnancy is progressing quickly. For many women, the halfway point feels emotionally significant. Some women may still worry about anatomy scans, baby''s health, body changes, and labor and parenting. Gentle reminder: It is normal to feel both excitement and anxiety during pregnancy.',
 '["Baby kicks and movement","Bloating","Constipation","Mild stretching sensations","Increased appetite","Emotional ups and downs","Mild back discomfort","Occasional dizziness"]',
 '["Continue prenatal vitamins","Stay hydrated","Eat balanced nutritious meals","Gentle physical activity if comfortable","Prioritize sleep and rest","Attend anatomy scan and prenatal appointments if scheduled","Wear supportive comfortable clothing","Continue avoiding smoking and alcohol"]',
 '["Heavy bleeding","Severe abdominal pain","Fever","Severe dizziness or fainting","Severe headaches with vision changes","Painful urination","Severe swelling or dehydration"]',
 '["Support healthy habits","Help with meals and snacks","Encourage rest and relaxation","Attend scans and appointments together","Share excitement about baby movement"]',
 'You are halfway through an incredible journey. Your baby is growing stronger, more active, and more developed every single day. Even on difficult days, your body is doing extraordinary work quietly behind the scenes. Rest, nourishment, hydration, movement, emotional support, and kindness toward yourself continue to be beautiful ways to care for both you and your growing baby.',
 '🍌', 'Banana', 16.4);
