-- Pregnancy guidance: Weeks 2–10
-- Paste into Supabase SQL Editor and run.

insert into public.pregnancy_guidance (
  week, baby_this_week, your_body, symptoms, important_nutrients,
  helpful_foods, things_to_limit, helpful_practices, good_habits,
  emotional_wellness, whats_normal, checklist, contact_doctor,
  partner_support, encouragement, baby_size_emoji, baby_size_object, baby_length_cm
) values

(2,
 'Your body is continuing to prepare for ovulation and possible conception. During Week 2, hormones continue changing, an egg begins maturing in the ovary, and the uterine lining thickens to support a future pregnancy. Ovulation may happen toward the end of this week for many women.',
 'Your body is entering the fertile phase of the menstrual cycle. Hormone levels begin increasing to support ovulation. Some women may notice increased energy, changes in cervical mucus, mild bloating, or slight pelvic discomfort. These changes are often related to ovulation preparation.',
 '["Mild bloating","Increased vaginal discharge","Breast sensitivity","Mild pelvic discomfort","Increased energy","Changes in mood"]',
 '["Folic acid","Iron","Protein","Calcium","Omega-3 fats","Hydration"]',
 '["Leafy greens","Fruits","Whole grains","Nuts and seeds","Eggs","Yogurt and dairy","Lentils and beans"]',
 '["Smoking","Alcohol","Excess caffeine","Highly processed foods"]',
 '["Gentle exercise or walking","Prioritize sleep","Manage stress","Stay hydrated","Track ovulation if desired"]',
 '["Continue prenatal vitamins","Focus on balanced meals","Reduce stress where possible","Spend time relaxing and resting"]',
 'Trying to conceive can bring many emotions. You may feel excited, hopeful, impatient, anxious, or emotional. Some women feel pressure during ovulation tracking or timing. Gentle reminder: You do not need to control every detail perfectly.',
 '["Mild bloating","Increased discharge","Emotional changes","Slight cramping","Increased energy","Changes in appetite"]',
 '["Continue prenatal vitamins","Stay hydrated","Eat balanced meals","Track ovulation if desired","Prioritize sleep","Reduce stress where possible","Limit smoking/alcohol/caffeine","Gentle physical activity"]',
 '["Severe pelvic pain","Unusually heavy bleeding","Fever","Severe dizziness","Ongoing fertility concerns","Significant menstrual irregularities"]',
 '["Reduce emotional pressure","Support healthy routines","Help with stress management","Participate in planning together","Offer reassurance and patience"]',
 'Your body is doing important preparation work this week, even if you cannot see it yet. Small healthy habits, rest, nourishment, and emotional care all help support your pregnancy journey beautifully. You are already taking meaningful steps toward caring for yourself and your future baby.',
 '🌱', 'Sesame seed', 0.2),

(3,
 'This is often the week when conception may happen. During Week 3, ovulation usually occurs, sperm and egg may meet, fertilization can happen, and the fertilized egg begins dividing into many cells. Your future baby is now a tiny group of rapidly growing cells traveling toward the uterus. Important genetic information like eye color, hair color, and biological sex is already determined at fertilization.',
 'Your body is going through important hormonal and reproductive changes. After ovulation, progesterone levels rise, the uterine lining thickens further, and the body prepares for possible implantation. Most women still do not feel pregnant yet during this stage.',
 '["Mild bloating","Breast tenderness","Fatigue","Increased discharge","Mild cramping","Mood changes"]',
 '["Folic acid","Protein","Iron","Calcium","Omega-3 fats","Hydration"]',
 '["Leafy greens","Fruits","Lentils and beans","Eggs","Nuts and seeds","Dairy products","Whole grains"]',
 '["Smoking","Alcohol","Excess caffeine","Raw or undercooked foods"]',
 '["Prioritize sleep","Gentle exercise or walking","Stay hydrated","Reduce stress","Eat balanced meals regularly"]',
 '["Continue prenatal vitamins","Avoid excessive exhaustion","Focus on emotional wellbeing","Rest when needed"]',
 'This stage can feel exciting, emotional, uncertain, hopeful, or stressful. Some women feel deeply aware of every small body sensation during the two-week wait. Others try not to think about it constantly. Both are completely valid.',
 '["No symptoms at all","Mild bloating","Emotional changes","Breast tenderness","Fatigue","Light cramping"]',
 '["Continue prenatal vitamins","Stay hydrated","Eat balanced meals","Prioritize sleep","Avoid smoking and alcohol","Reduce excess caffeine","Gentle physical activity","Focus on stress management"]',
 '["Severe pelvic pain","Heavy bleeding","Fever","Severe dizziness","Unusual reproductive symptoms","Ongoing fertility concerns"]',
 '["Reduce stress and pressure","Offer emotional reassurance","Support healthy habits","Be patient during uncertainty","Participate in the journey together"]',
 'Even though everything is still microscopic right now, incredible changes may already be beginning inside your body. Your body is working quietly and beautifully behind the scenes. Small moments of rest, nourishment, care, and hope all matter during this early stage of the journey.',
 '🫐', 'Blueberry', 0.3),

(4,
 'This is often the week when implantation may happen and early pregnancy officially begins. The fertilized egg, now called a blastocyst, travels into the uterus and may attach to the uterine lining. Tiny early structures begin forming that will later develop into the placenta, amniotic sac, and embryo. Your baby is still extremely tiny — about the size of a poppy seed.',
 'Your body begins producing more pregnancy hormones, especially hCG (human chorionic gonadotropin). These hormonal changes help support implantation and early pregnancy development. Some women may begin noticing very early pregnancy symptoms during this week, while others notice nothing yet. Both can be normal.',
 '["Missed period","Mild cramping","Breast tenderness","Fatigue","Bloating","Emotional changes","Increased discharge","Light spotting (implantation spotting)"]',
 '["Folic acid","Iron","Protein","Calcium","Omega-3 fats","Hydration"]',
 '["Leafy greens","Fruits","Lentils and beans","Eggs","Dairy products","Nuts and seeds","Whole grains"]',
 '["Smoking","Alcohol","Excess caffeine","Raw or undercooked foods"]',
 '["Prioritize rest","Gentle walking or stretching","Stay hydrated","Reduce stress","Eat small balanced meals"]',
 '["Continue prenatal vitamins","Avoid overexertion","Listen to your body","Rest when tired"]',
 'Week 4 can feel emotionally intense for many women. You may feel excited, nervous, overwhelmed, hopeful, or anxious. Some women may take a pregnancy test this week and begin processing the reality of pregnancy. Others may still be waiting or uncertain. All feelings are valid.',
 '["Mild cramping","Bloating","Fatigue","Breast tenderness","Emotional changes","Little or no symptoms"]',
 '["Continue prenatal vitamins","Stay hydrated","Eat balanced meals","Prioritize sleep and rest","Avoid smoking and alcohol","Reduce excess caffeine","Take pregnancy test if period is missed","Schedule first doctor appointment if needed"]',
 '["Heavy bleeding","Severe abdominal pain","Severe dizziness","Fever","Fainting","Severe one-sided pain"]',
 '["Offer emotional reassurance","Reduce stress","Support healthy habits","Celebrate small moments together","Help create a calm environment"]',
 'Even though your baby is still incredibly tiny, important changes may already be happening inside your body. This early stage can feel emotional, exciting, and uncertain all at once. You do not need to have everything figured out right now. Rest, nourishment, hydration, and gentle self-care are already beautiful ways to support your growing journey.',
 '🌱', 'Poppy seed', 0.4),

(5,
 'Your baby is growing incredibly fast this week. The tiny embryo is now about the size of a sesame seed. Important early development begins, including brain development, spinal cord formation, heart formation, and early circulatory system development. The neural tube, which later becomes the brain and spinal cord, continues developing rapidly. Tiny beginnings of arms, legs, and facial features are also starting to form.',
 'Pregnancy hormones continue rising quickly during Week 5. Your body is working hard to support implantation, hormone production, placenta development, and early pregnancy growth. Many women begin noticing stronger pregnancy symptoms this week. Fatigue may increase significantly.',
 '["Missed period","Fatigue","Breast tenderness","Bloating","Nausea beginning","Food aversions","Emotional changes","Increased urination"]',
 '["Folic acid","Protein","Iron","Calcium","Omega-3 fats","Hydration"]',
 '["Leafy greens","Fruits","Yogurt and dairy","Lentils and beans","Eggs","Nuts and seeds","Whole grains"]',
 '["Alcohol","Smoking","Excess caffeine","Raw or undercooked foods"]',
 '["Prioritize sleep","Gentle walking","Rest when tired","Stay hydrated","Eat regularly"]',
 '["Continue prenatal vitamins","Reduce stress where possible","Avoid overexertion","Listen to your body"]',
 'Week 5 can feel emotionally overwhelming for many women. You may feel excited, anxious, emotional, grateful, nervous, or exhausted. Some women may begin worrying about miscarriage, symptoms, scans, or doing everything right. Gentle reminder: You do not need to be perfect to support your pregnancy.',
 '["Fatigue","Nausea","Sore breasts","Bloating","Mood changes","Food cravings or aversions","Little or no symptoms"]',
 '["Continue prenatal vitamins","Stay hydrated","Eat balanced meals","Prioritize sleep and rest","Avoid smoking and alcohol","Reduce excess caffeine","Begin researching prenatal care if needed","Schedule first prenatal appointment"]',
 '["Heavy bleeding","Severe abdominal pain","Severe dizziness","Fainting","Fever","Severe one-sided pelvic pain","Persistent vomiting causing dehydration"]',
 '["Offer emotional reassurance","Help with meals and snacks","Reduce stress","Support rest and sleep","Attend appointments together"]',
 'Your body is doing incredible work right now — even if much of it is invisible. Tiny beginnings are growing every single day. Rest, nourishment, hydration, and kindness toward yourself are more than enough during this early stage of the journey.',
 '🌱', 'Sesame seed', 0.5),

(6,
 'Your baby is growing rapidly this week. The embryo is now about the size of a lentil. Major development is happening, including early brain development, spinal cord growth, heart development, and formation of tiny arm and leg buds. In many pregnancies, the heartbeat may begin to be detectable around this stage. Even though your baby is still very tiny, important organs and body systems are developing quickly.',
 'Pregnancy hormones increase significantly during Week 6. Your body is working hard to support placenta development, hormone production, early fetal growth, and increased blood supply. Many women begin feeling stronger pregnancy symptoms during this stage. Fatigue may become more noticeable.',
 '["Nausea or morning sickness","Fatigue","Breast tenderness","Bloating","Food cravings or aversions","Mood changes","Increased urination","Heightened sense of smell"]',
 '["Folic acid","Protein","Iron","Calcium","Omega-3 fats","Hydration"]',
 '["Leafy greens","Fruits","Lentils and beans","Yogurt and dairy","Eggs","Nuts and seeds","Whole grains"]',
 '["Alcohol","Smoking","Excess caffeine","Raw or undercooked foods"]',
 '["Prioritize rest","Gentle walking or stretching","Sleep early when possible","Stay hydrated","Eat regularly"]',
 '["Continue prenatal vitamins","Listen to your body","Avoid overexertion","Take breaks when tired"]',
 'Week 6 can feel emotionally intense for many women. You may feel excited, anxious, emotional, overwhelmed, grateful, or worried. Some women begin worrying about miscarriage, fluctuating symptoms, upcoming scans, or whether everything is progressing normally. Gentle reminder: Pregnancy symptoms can vary greatly from person to person and even day to day.',
 '["Nausea","Fatigue","Bloating","Sore breasts","Food aversions","Emotional ups and downs","Little or no symptoms"]',
 '["Continue prenatal vitamins","Stay hydrated","Eat small balanced meals","Prioritize sleep and rest","Avoid smoking and alcohol","Reduce excess caffeine","Schedule first prenatal appointment if not done","Begin noting important questions for doctor visits"]',
 '["Heavy bleeding","Severe abdominal pain","Fever","Severe dizziness","Fainting","Severe one-sided pelvic pain","Persistent vomiting causing dehydration"]',
 '["Help with meals and snacks","Reduce stress","Offer emotional reassurance","Help with household tasks","Attend appointments together"]',
 'Your body is doing incredible work right now — even on days when you feel exhausted. Tiny beginnings are growing and developing every single moment. You do not need to handle everything perfectly. Rest, nourishment, hydration, and kindness toward yourself are already powerful ways to care for both you and your growing baby.',
 '🫛', 'Sweet pea', 0.6),

(7,
 'Your baby is growing rapidly and becoming more recognizable this week. Your baby is now about the size of a blueberry. Important development continues, including brain growth, facial feature development, heart development, and arm and leg growth. Tiny hands and feet begin forming, although they still look very small and delicate. The brain and nervous system are developing quickly during this stage.',
 'Pregnancy hormones continue rising rapidly during Week 7. Your body is working hard to support placenta growth, increased blood flow, hormone production, and early fetal development. Fatigue and nausea may become stronger during this week for many women. Your body is using enormous energy internally, even if you cannot see it.',
 '["Nausea or morning sickness","Strong fatigue","Breast tenderness","Bloating","Food cravings or aversions","Increased urination","Emotional sensitivity","Stronger sense of smell"]',
 '["Folic acid","Protein","Iron","Calcium","Omega-3 fats","Hydration"]',
 '["Fruits","Leafy greens","Lentils and beans","Eggs","Yogurt and dairy","Whole grains","Nuts and seeds"]',
 '["Alcohol","Smoking","Excess caffeine","Raw or undercooked foods"]',
 '["Prioritize rest","Gentle walking","Light stretching if comfortable","Stay hydrated","Take breaks often"]',
 '["Continue prenatal vitamins","Listen to your body","Avoid overexertion","Sleep whenever needed"]',
 'Week 7 can feel emotionally overwhelming. You may feel excited, anxious, emotional, exhausted, grateful, or worried. Some women may worry about miscarriage, symptom changes, scan appointments, or whether baby is growing properly. Gentle reminder: Pregnancy symptoms naturally fluctuate from day to day.',
 '["Nausea","Fatigue","Bloating","Sore breasts","Emotional changes","Food aversions","Constipation","Little or no symptoms"]',
 '["Continue prenatal vitamins","Stay hydrated","Eat small balanced meals","Prioritize sleep and rest","Avoid smoking and alcohol","Reduce excess caffeine","Prepare questions for first prenatal visit","Listen to your body and slow down when needed"]',
 '["Heavy bleeding","Severe abdominal pain","Fever","Fainting","Severe dizziness","Severe one-sided pelvic pain","Persistent vomiting causing dehydration"]',
 '["Help with meals and snacks","Offer emotional reassurance","Support extra rest","Reduce stress","Help with household tasks"]',
 'Your body is doing remarkable work every single day. Even when you feel tired, emotional, or overwhelmed, important growth and development are happening quietly inside you. You are not expected to do everything perfectly. Rest, nourishment, hydration, and kindness toward yourself are already beautiful ways to care for your growing baby.',
 '🫐', 'Blueberry', 1.0),

(8,
 'Your baby is growing rapidly and becoming more developed this week. Your baby is now about the size of a raspberry. Important development continues, including brain growth, facial feature formation, heart development, tiny fingers and toes forming, and early movement beginning. Although you cannot feel movement yet, your baby may already be making tiny movements inside the womb. Major organs continue developing rapidly during this stage.',
 'Pregnancy hormones remain very high during Week 8. Your body is working hard to support placenta development, increased blood flow, hormone production, and baby''s rapid growth. Many women feel stronger pregnancy symptoms during this stage, especially fatigue and nausea. Your uterus is also continuing to grow gradually.',
 '["Nausea or morning sickness","Strong fatigue","Breast tenderness","Bloating","Food cravings or aversions","Constipation","Headaches","Increased urination","Emotional sensitivity"]',
 '["Folic acid","Protein","Iron","Calcium","Omega-3 fats","Hydration"]',
 '["Fruits","Leafy greens","Whole grains","Lentils and beans","Yogurt and dairy","Eggs","Nuts and seeds"]',
 '["Alcohol","Smoking","Excess caffeine","Raw or undercooked foods"]',
 '["Prioritize rest","Gentle walking","Light stretching if comfortable","Stay hydrated","Take breaks often"]',
 '["Continue prenatal vitamins","Listen to your body","Avoid overexertion","Sleep whenever needed"]',
 'Week 8 can feel emotionally overwhelming. You may feel excited, emotional, anxious, exhausted, grateful, or nervous. Some women may worry about upcoming scans, miscarriage, symptom changes, or whether baby is developing normally. Gentle reminder: Every pregnancy journey looks different.',
 '["Nausea","Fatigue","Bloating","Sore breasts","Constipation","Emotional changes","Food aversions","Little or no symptoms"]',
 '["Continue prenatal vitamins","Stay hydrated","Eat small balanced meals","Prioritize sleep and rest","Avoid smoking and alcohol","Reduce excess caffeine","Prepare for prenatal appointments","Rest when your body asks for it"]',
 '["Heavy bleeding","Severe abdominal pain","Fever","Fainting","Severe dizziness","Severe one-sided pelvic pain","Persistent vomiting causing dehydration"]',
 '["Help with meals and snacks","Support extra rest","Reduce stress","Offer emotional reassurance","Help with household responsibilities"]',
 'Your body is doing extraordinary work right now. Even on difficult days, incredible development is happening quietly inside you every single moment. You do not need to handle pregnancy perfectly. Rest, nourishment, hydration, and self-kindness are already beautiful ways to care for yourself and your growing baby.',
 '🍓', 'Raspberry', 1.6),

(9,
 'Your baby is growing rapidly and now officially enters the fetal stage. Your baby is about the size of a cherry or green olive. Important development continues, including rapid brain growth, stronger heartbeat, facial features becoming clearer, tiny fingers and toes becoming more defined, and early muscle and body movement. Although you still cannot feel movement yet, your baby may already be moving inside the uterus. Major organs continue developing and maturing during this stage.',
 'Pregnancy hormones remain very high during Week 9. Your body continues supporting placenta growth, increased blood supply, hormone production, and baby''s rapid development. Many women still experience strong first-trimester symptoms during this week. Your uterus continues slowly expanding, even if there is little visible bump yet.',
 '["Nausea or morning sickness","Fatigue","Breast tenderness","Bloating","Food cravings or aversions","Constipation","Headaches","Emotional sensitivity","Increased urination"]',
 '["Folic acid","Protein","Iron","Calcium","Omega-3 fats","Fiber","Hydration"]',
 '["Fruits","Leafy greens","Whole grains","Lentils and beans","Yogurt and dairy","Eggs","Nuts and seeds"]',
 '["Alcohol","Smoking","Excess caffeine","Raw or undercooked foods"]',
 '["Prioritize rest","Gentle walking","Light stretching if comfortable","Stay hydrated","Take breaks often"]',
 '["Continue prenatal vitamins","Listen to your body","Avoid overexertion","Sleep whenever needed"]',
 'Week 9 can feel emotionally intense. You may feel excited, emotional, anxious, overwhelmed, grateful, or nervous. Some women may worry about miscarriage, fluctuating symptoms, upcoming scans, or whether baby is growing normally. Gentle reminder: Symptom intensity can naturally change from day to day.',
 '["Nausea","Fatigue","Bloating","Sore breasts","Emotional changes","Constipation","Food aversions","Little or no symptoms"]',
 '["Continue prenatal vitamins","Stay hydrated","Eat small balanced meals","Prioritize sleep and rest","Avoid smoking and alcohol","Reduce excess caffeine","Attend prenatal appointments if scheduled","Rest when your body needs it"]',
 '["Heavy bleeding","Severe abdominal pain","Fever","Fainting","Severe dizziness","Severe one-sided pelvic pain","Persistent vomiting causing dehydration"]',
 '["Help with meals and snacks","Offer emotional reassurance","Support extra rest","Reduce stress","Attend appointments together"]',
 'Your baby is growing and developing in amazing ways every single day. Even when pregnancy feels exhausting or emotional, your body is doing extraordinary work quietly behind the scenes. You do not need to do everything perfectly. Rest, nourishment, hydration, and gentle self-care are already beautiful ways to support yourself and your growing baby.',
 '🍇', 'Grape', 2.3),

(10,
 'Your baby is growing quickly and becoming more developed every day. Your baby is now about the size of a strawberry. Important development continues, including rapid brain growth, stronger heartbeat, fingers and toes fully separated, tiny nails beginning to form, and early joints and limbs moving. Your baby may already be stretching, kicking, and moving tiny arms and legs, although you still cannot feel these movements yet. Major organs continue developing and beginning to function.',
 'Your body continues adjusting to rising pregnancy hormones and your growing baby. During Week 10, blood volume continues increasing, the uterus grows larger, hormone levels remain high, and metabolism works harder to support pregnancy. Many women still experience strong first-trimester symptoms, especially fatigue and nausea. Some women may also begin noticing tighter clothes or mild belly fullness.',
 '["Nausea or morning sickness","Fatigue","Bloating","Breast tenderness","Constipation","Headaches","Food cravings or aversions","Emotional sensitivity","Increased urination"]',
 '["Folic acid","Protein","Iron","Calcium","Omega-3 fats","Fiber","Hydration"]',
 '["Fruits","Vegetables","Whole grains","Lentils and beans","Yogurt and dairy","Eggs","Nuts and seeds"]',
 '["Alcohol","Smoking","Excess caffeine","Raw or undercooked foods"]',
 '["Prioritize rest","Gentle walking","Light stretching","Stay hydrated","Take breaks often"]',
 '["Continue prenatal vitamins","Listen to your body","Avoid overexertion","Rest when tired"]',
 'Week 10 can feel emotionally intense and exciting. You may feel excited, emotional, anxious, overwhelmed, grateful, or impatient. Some women may worry about scans and appointments, miscarriage, fluctuating symptoms, or whether baby is developing normally. Gentle reminder: Pregnancy emotions can change quickly due to hormones, exhaustion, and uncertainty.',
 '["Nausea","Fatigue","Bloating","Emotional ups and downs","Sore breasts","Constipation","Food aversions","Little or no symptoms"]',
 '["Continue prenatal vitamins","Stay hydrated","Eat small balanced meals","Prioritize sleep and rest","Avoid smoking and alcohol","Reduce excess caffeine","Attend prenatal appointments if scheduled","Prepare questions for upcoming scans and checkups"]',
 '["Heavy bleeding","Severe abdominal pain","Fever","Fainting","Severe dizziness","Severe one-sided pelvic pain","Persistent vomiting causing dehydration"]',
 '["Help with meals and snacks","Support rest and sleep","Reduce stress","Offer emotional reassurance","Attend appointments together"]',
 'Your baby is growing and developing in incredible ways every single day. Even if pregnancy feels exhausting or emotional right now, your body is doing remarkable work quietly behind the scenes. You do not need to do everything perfectly. Rest, nourishment, hydration, and kindness toward yourself are already beautiful ways to support both you and your growing baby.',
 '🍓', 'Strawberry', 3.1);
